### PR TITLE
feat(ts): Initial typescript version of guide.

### LINKED ISSUE #69: [Question] Typescript specifc remarks / info?
Hey Todd, 
What would be your opinion about including some typescript related info into you guide? 
If PRs are welcome, should those be included as a new chapter, or inline? I guess a new chapter would be less disturbing overall, but easier to miss...

### PR DESCRIPTION
**Pull request by laskoviymishka**
Add specific folder and initial `en-US` version of a document.
After initial doc merging adding `i18n` folder to it would be much easier.

Closes #69

### CODE REVIEW

**Comment by toddmotto** [comment]
Hey @laskoviymishka ! So, we made a few edits to the current styleguide. Essentially dropping `*.controller.js` and adding it as an ES6 `class` on the `controller:` props, would you be able to grab the latest changes please and jig things around to fit? :) would love to merge this!

**Comment by laskoviymishka** [comment]
@toddmotto sure, I love this part. But should you mind if I recommend to use some decorators for this instead of your way? I guide there will be same as es6 version, but in TS there is a lot of awesomeness that comes from decorators world (like this one https://github.com/MikeRyan52/angular-decorators)

**Comment by toddmotto** [comment]
For the guide, as "vanilla Angular" as possible, however we can add a better "Potential recommendations" I think, citing something like `ngMetadata` and `ngForward` etc. :)

**Comment by laskoviymishka** [comment]
@toddmotto well `vanilla` angular totally make sense. Let skip this part to later one :)

**Comment by toddmotto** [comment]
Hey, sorry for the delay with checking this - is it reviewable now? :)

**Comment by laskoviymishka** [comment]
yep

**Comment by toddmotto** [comment]
This is amazing - thank you so much! :)

**Pull request merged**
