### PR TITLE
Fix missing name property for module export

### PR DESCRIPTION
**Pull request by floriangosse**

### CODE REVIEW

**Comment by toddmotto** [comment]
Thanks man, any chance you can pull + merge then I can merge? :)

**Comment by floriangosse** [comment]
Yes, no problem. I will merge it.. :)

**Comment by floriangosse** [comment]
I rebased the branch to the latest version of master.

**Comment by floriangosse** [comment]
Is there something wrong?

**Comment by toddmotto** [comment]
Sorry dude, slipped through the net. Caught again and merged ! :D thanks!

**Pull request merged**
