### PR TITLE
Translation to Spanish

### PR DESCRIPTION
**Pull request by josueggh**
Many people in LATAM don't understand the english. This is only a translation of your guide.

### CODE REVIEW

**Comment by toddmotto** [comment]
Wow thank you very much for this! Amazing work. In the next few months, I will be updating the guide to cater for Angular 1.5 (which changes a _lot_), if you have some time any updates to your i18n version are much appreciated, thank you!

**Comment by josueggh** [comment]
For sure! 👍

**Comment by toddmotto** [comment]
Awesome, thanks again, super appreciate the contribution.

**Comment by LucasCaixeta** [comment]
And what about translate to Portuguese? I can do this! :) :+1:

**Comment by toddmotto** [comment]
Sure! If anyone reading wants to submit something that'd be awesome. Appreciate the efforts. Perhaps hold off until the new guide is completed. If you guys want to help contribute to the guide then that's also awesome! :)

**Comment by LucasCaixeta** [comment]
No problem, I´ll wait for the new version to translate. And thank you for every effort, this guide is one of the best I have ever read about angular. :+1:  =)

**Comment by toddmotto** [comment]
Awesome! Keep an eye out! :) and hey thanks for helping, it's been awesome putting it together.

**Comment by UnJavaScripter** [comment]
Cool!! I'll help with the spanish translation.

How about going es-LA instead of "limiting" it to countries @josueggh? I have experience with _spanish-neutral_ writting.

**Comment by josueggh** [comment]
:) for sure @UnJavaScripter

**Comment by toddmotto** [comment]
New guide is out: https://github.com/toddmotto/angular-styleguide/commit/f9338ae621f51b089034dc2ac52dc676f5ed88f5

**Pull request merged**
