### PR TITLE
Updates to reflect latest Angular 2 conventions

### PR DESCRIPTION
**Pull request by richardsolomou**

### CODE REVIEW

**Comment by toddmotto** [comment]
I really like this, have also been thinking similarly: https://github.com/toddmotto/angular-1-5-components-app/blob/master/src/app/components/auth/auth.module.js

Would you be able to update the other `i18n` files with the code updates so I can get it merged? Thank you! :)

**Comment by toddmotto** [comment]
Amazing PR - thanks so much. Using *.module.js makes more sense to me. Entry points can be changed if they feel like it which is also nice.

**Comment by richardsolomou** [comment]
Hey Todd, glad you like it! I've been using this variant for our codebase for a couple weeks and thought it made more sense to do it this way in order to make the switch to Angular 2 even easier. Hopefully this also eases the concerns some people have with having too many index.js files lying around!

**Comment by toddmotto** [comment]
Definitely, really appreciate the PR and your time spent on it!

**Pull request merged**
