### PR TITLE
Update component template examples

### PR DESCRIPTION
**Pull request by GabrielGil**
Component templates should be specified either on the property `template` or in `templateUrl`.

Currently the examples include a hypothetical templateUrl directly inside an object.

Reference: [Angular Components](https://docs.angularjs.org/guide/component).

### CODE REVIEW

**Comment by toddmotto** [comment]
I'm not sure what's wrong here, the current implementation is correct based on the code, if it's an HTML file it needs `templateUrl`.

**Comment by xavhan** [comment]
If you import content from html file you get HTML so you need to put it in the template property of the component object.

**Comment by GabrielGil** [comment]
Exactly, @xavhan is right. In the original styleguide, the import is not assigned to a component object parameter. Neither `template` or `templateUrl`.

**Comment by toddmotto** [comment]
If you import a string, you do - an HTML file is not a string. Try out the live app that this repo's readme links to - it follows this guide and structure

**Comment by toddmotto** [comment]
Try the live app the style guide links to it uses templateUrl, for example: https://github.com/toddmotto/angular-1-5-components-app/blob/ES2015/src/app/components/auth/auth-form/auth-form.component.js



@toddmotto

**Comment by GabrielGil** [comment]
Ok, now I see that on that example app you use `ngTemplate` loader as suggested on [tooling](https://github.com/toddmotto/angular-styleguide#tooling). I was expecting a regular html loader. Maybe what mixed me up was using a tool that was just "to be considered".

**Comment by toddmotto** [comment]
Ah sorry! Let me work on making this clearer. Sorry for the confusion!

**Comment by GabrielGil** [comment]
In my opinion, it'd be more clear if either the guide removes the "consideration" of `ngTemplate` and indicates that it is being actually used, or adapting the examples to be valid without the `ngTemplate` loader. This would be:

``` js
 /* ----- todo/todo.component.js ----- */
import template from './todo.html';
 
 export const TodoComponent = {
  template,
  controller: class TodoComponent {
  constructor(TodoService) {
        'ngInject';
  }
  // [...]
}
```

**Comment by toddmotto** [comment]
Yeah, I'm only using it here as the guide is focused on ES6 etc, thus tooling will be provided.  Will rework the example when I have some time :)

**Comment by xavhan** [comment]
@GabrielGil  would you mind closing this PR? It is still appearing in Pull-Requests `Mentioned` and I cant hide that it triggers my OCDs :D 

Thanks :D

**Comment by GabrielGil** [comment]
Sure!

**Pull request closed without merging**
